name: 1. 서명키 만들기

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest
    steps:
      - name: 서명키 생성
        run: |
          keytool -genkeypair -v \
            -keystore upload.jks \
            -alias upload \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -dname "CN=Pushup, OU=None, O=None, L=Sokcho, S=Gangwon, C=KR"
          echo "===== 여기서부터 복사 ====="
          base64 -w 0 upload.jks
          echo ""
          echo "===== 여기까지 복사 ====="

      - name: 결과 내려받기
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: upload.jks
